force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Event_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Event_Confirmation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Confirmation</label>
    <referenceTo>Event_Confirmation__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Event_Question__c.field-meta.xml
<CustomField>
    <fullName>Event_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Question</label>
    <referenceTo>Event_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Send_Event_Confirmation_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Event_Confirmation_Emails__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send Event Confirmation Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Time_ZoneStr__c.field-meta.xml
<CustomField>
    <fullName>Time_ZoneStr__c</fullName>
    <label>Time Zone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Code__c</fullName>
    <label>Confirmation Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvAddress__c.field-meta.xml
<CustomField>
    <fullName>EvAddress__c</fullName>
    <formula>Custom_Event__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateEnd__c.field-meta.xml
<CustomField>
    <fullName>EvDateEnd__c</fullName>
    <formula>MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 0, 4) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 6, 2) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440) ), 9, 2) &amp; &quot;T&quot; &amp;
LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateEnd</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStart__c.field-meta.xml
<CustomField>
    <fullName>EvDateStart__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;T&quot; &amp;  LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStart</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvEmail__c.field-meta.xml
<CustomField>
    <fullName>EvEmail__c</fullName>
    <formula>Custom_Event__r.Host__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvHostName__c.field-meta.xml
<CustomField>
    <fullName>EvHostName__c</fullName>
    <formula>Custom_Event__r.Host__r.FirstName &amp; &quot; &quot; &amp; Custom_Event__r.Host__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvHostName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvName__c.field-meta.xml
<CustomField>
    <fullName>EvName__c</fullName>
    <formula>Custom_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>$Label.Community_URL &amp; &quot;/check-in/?id=&quot; &amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/Event_Question__c.object-meta.xml
<CustomObject>
    <label>Event Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Question__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Questions</relationshipLabel>
    <relationshipName>Event_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>Write your picklist, each option in a single line</inlineHelpText>
    <label>Options</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/fields/Type_of_Question__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Question__c</fullName>
    <label>Type of Question</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Text</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventConfirmationController.cls
/**
 * @description       : eventConfirmationForm Controller
 * @author            : Eduardo Hernandez
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
public without sharing class EventConfirmationController {
    @AuraEnabled(cacheable = true)
    public static Map<String, Object> getCustomEvent(String id) {
        final Map<String, Object> response = new Map<String, Object>();
        try {
            final Custom_Event__c eventRecord = [SELECT Name, Date__c, Time_ZoneStr__c, 
            Address__c, Duration__c, Minutes_Or_Hours__c, Purpose__c, 
            Status__c, Host__r.Name, Timezone__c,
            (SELECT Id, Name, Type_of_Question__c, Options__c, Required__c FROM Event_Questions__r)
            FROM Custom_Event__c WHERE Id =: id LIMIT 1];
            response.put('eventRecord', eventRecord);
            response.put('formateDate', ScheduledEventCalendar_Ctrl.findTimeZones(id));
            response.put('isOk', true);
            response.put('nameuser', System.UserInfo.getName());
        } catch (Exception e) {
            response.put('isOk', false);
            response.put('isOk', e.getMessage());
        } 
        return response;
    }

    @AuraEnabled(cacheable = false)
    public static Id createEventConfirmation(Id eventId, String firstName, String lastName, String email){
        Event_Confirmation__c eventConf = new Event_Confirmation__c(Guest_First_Name__c = firstName,
        Guest_Last_Name__c = lastName, Custom_Event__c = eventId, Email__c = email);
        Contact[] contact = [SELECT Id FROM Contact WHERE Email =: email LIMIT 1];    
        if(contact.size() > 0){
            eventConf.Contact__c = contact[0].id;
        }

        insert eventConf;
        return eventConf.Id;
    }

    @AuraEnabled(cacheable = false)
    public static void answersList(List<Map<String,String>> object2, Id eventConfirmationId){
        List<Answer__c> answers = new List<Answer__c>();
        for (Map<String,String> obj : object2) {
            Event_Question__c eventQuestion = [SELECT Id FROM Event_Question__c WHERE Id =: obj.get('key')];
            Answer__c answer = new Answer__c(Event_Confirmation__c = eventConfirmationId);
            answer.Event_Question__c = eventQuestion.Id;
            if(obj.get('value') == 'true'){
                answer.Name = 'Yes';
            }
            else if(obj.get('value') == 'false') {
                answer.Name = 'No';
            }
            else {
                answer.Name = obj.get('value');
            }
            answers.add(answer);
        }
        insert answers;
        Event_Confirmation__c eventSend = [SELECT Id, Custom_Event__r.Send_Event_Confirmation_Emails__c FROM Event_Confirmation__c WHERE Id =: eventConfirmationId];
        if(eventSend.Custom_Event__r.Send_Event_Confirmation_Emails__c){
            Event_Confirmation__c event = [SELECT Id, Guest_First_Name__c, Guest_Last_Name__c,
            Email__c, Contact__c, Custom_Event__c, EvName__c FROM Event_Confirmation__c WHERE Id =: eventConfirmationId];
        
            List<Answer__c> answersEmail = [SELECT Name, Event_Question__r.Name FROM Answer__c WHERE Event_Confirmation__c =: eventConfirmationId];

            EventConfirmationEmailHandler handler = new EventConfirmationEmailHandler();
            
            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
            
            
            Messaging.SingleEmailMessage mailHostOrganizer = handler.hostOrganizerEmail(event, answers);

            emailList.add(mailHostOrganizer);

            Messaging.sendEmail(emailList);
        }
    }

    @AuraEnabled
    public static Map<String, Object> generateICS(String recordId) {
        final Map<String, Object> response = new Map<String, Object>();
        try {
            Event_Confirmation__c eventConfirmation = [Select Id, EvDateStart__c, EvDateEnd__c, EvName__c, URL__c, Confirmation_Code__c, EvHostName__c, 
            EvEmail__c, EvAddress__c from Event_Confirmation__c where Id =: recordId limit 1];
            response.put('base64file', EventConfirmationController.generateICSBase64(eventConfirmation));
            response.put('eventConfirm', eventConfirmation);
            response.put('isOk', true);
        } catch (QueryException quEx) {
            response.put('isOk', false);
            response.put('msjError', quEx.getMessage());
        }
        return response;
    }

    private static String generateICSBase64(Event_Confirmation__c eventConfirmation) {
        String baseStr = '';
        String icsfile = EventConfirmationController.generateICSfile(eventConfirmation);
        Blob baseStrblob = Blob.valueOf(icsfile);
        baseStr = EncodingUtil.base64Encode(baseStrblob);
        return baseStr;
    }

    private static String generateICSfile(Event_Confirmation__c eventConfirmation) {
        String icsFile = 'BEGIN:VCALENDAR' + '\n' +
            'VERSION:2.0' +  '\n' +
            'PRODID:-//hacksw/handcal//NONSGML v1.0//EN' + '\n' +
            'BEGIN:VEVENT' + '\n' +
            'UID:uid1@example.com' + '\n' +
            'DTSTAMP:' + eventConfirmation.EvDateStart__c + 'Z' + '\n' +
            'DTSTART:' + eventConfirmation.EvDateStart__c + 'Z' + '\n' +
            'DTEND:' + eventConfirmation.EvDateEnd__c + 'Z' + '\n' +
            'SUMMARY:' + eventConfirmation.EvName__c + '\n' +
            'DESCRIPTION:Check in Link: ' + eventConfirmation.URL__c + '\n' +
            '  \\nCode: ' + eventConfirmation.Confirmation_Code__c + '\n' +
            '  \\n**Check in:  From 2 hours before the event start up to 2 hours after the event started**' + '\n' +
            'ORGANIZER;CN=' + eventConfirmation.EvHostName__c + ':mailto:' + eventConfirmation.EvEmail__c + '\n' +
            'STATUS:CONFIRMED' + '\n' +
            'LOCATION:' + eventConfirmation.EvAddress__c + '\n' +
            'BEGIN:VALARM' + '\n' +
            'ACTION:DISPLAY' + '\n' +
            'TRIGGER:-PT2H'  + '\n' +
            'END:VALARM'  + '\n' +
            'END:VEVENT' + '\n' +
            'END:VCALENDAR';
        return icsFile;
    }
}