force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Event_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Event_Confirmation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Confirmation</label>
    <referenceTo>Event_Confirmation__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Event_Question__c.field-meta.xml
<CustomField>
    <fullName>Event_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Question</label>
    <referenceTo>Event_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Code__c</fullName>
    <label>Confirmation Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvAddress__c.field-meta.xml
<CustomField>
    <fullName>EvAddress__c</fullName>
    <formula>Custom_Event__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateEnd__c.field-meta.xml
<CustomField>
    <fullName>EvDateEnd__c</fullName>
    <formula>MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 0, 4) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 6, 2) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440) ), 9, 2) &amp; &quot;T&quot; &amp;
LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateEnd</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStart__c.field-meta.xml
<CustomField>
    <fullName>EvDateStart__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;T&quot; &amp;  LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStart</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStartDisplay__c.field-meta.xml
<CustomField>
    <fullName>EvDateStartDisplay__c</fullName>
    <formula>LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; &quot; &quot; &amp; 
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))  &gt;  12, LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c + 12 )/24)))),2,&quot;0&quot;), LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))),2,&quot;0&quot;)) &amp; &quot;:&quot; &amp; 
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)&amp; &quot; &quot; &amp;
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24))) &gt;= 12, &apos;PM&apos;, &apos;AM&apos;)
&amp; &quot; &quot; &amp;
TEXT(Custom_Event__r.Timezone__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStartDisplay</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvEmail__c.field-meta.xml
<CustomField>
    <fullName>EvEmail__c</fullName>
    <formula>Custom_Event__r.Host__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvHostName__c.field-meta.xml
<CustomField>
    <fullName>EvHostName__c</fullName>
    <formula>Custom_Event__r.Host__r.FirstName &amp; &quot; &quot; &amp; Custom_Event__r.Host__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvHostName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvName__c.field-meta.xml
<CustomField>
    <fullName>EvName__c</fullName>
    <formula>Custom_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>$Label.Community_URL &amp; &quot;/check-in/?id=&quot; &amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/Event_Question__c.object-meta.xml
<CustomObject>
    <label>Event Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Question__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Questions</relationshipLabel>
    <relationshipName>Event_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventConfirmationEmailHandlerTest.cls
/**
 * @description       : 
 * @author            : Eduardo Hernandez
 * @group             : 
 * @last modified on  : 11-03-2023
 * @last modified by  : Eduardo Hernandez
**/
@isTest
private class EventConfirmationEmailHandlerTest {
    @TestSetup
    static void makeData() {
        Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);
        Custom_Event__c testEvent = new Custom_Event__c();
        testEvent.Name = 'Test Event';
        testEvent.Timezone__c = 'CST';
        testEvent.Address__c = 'Address';
        testEvent.Duration__c = 60;
        testEvent.Minutes_Or_Hours__c = 'Minutes';
        testEvent.Date__c = Datetime.now() + 8;
        testEvent.Host__c = UserInfo.getUserId();
        insert testEvent;
        
        Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
        Event_Confirmation__c testConfirm = new Event_Confirmation__c(
            Guest_First_Name__c = 'First', Guest_Last_Name__c = 'Last',
            Email__c = 'email@email.com', Check_In__c = false,
            Custom_Event__c = eventId
        );
        insert testConfirm;

        Custom_Event__c testEventHost = new Custom_Event__c();
        User userEmail = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        testEventHost.Name = 'Test Event Host';
        testEventHost.Timezone__c = 'CST';
        testEventHost.Address__c = 'Address';
        testEventHost.Duration__c = 60;
        testEventHost.Minutes_Or_Hours__c = 'Minutes';
        testEventHost.Date__c = Datetime.now() + 8;
        testEventHost.Host__c = userEmail.Id;
        insert testEventHost;

        Id eventIdHost = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event Host'].Id;
        Event_Confirmation__c testConfirmHost = new Event_Confirmation__c(
            Guest_First_Name__c = 'First Host', Guest_Last_Name__c = 'Last Host',
            Email__c = 'email@email.com', Check_In__c = false,
            Custom_Event__c = eventIdHost
        );

        Event_Question__c eventQuestion = new Event_Question__c(Name = 'Question', Custom_Event__c = eventId);
        insert eventQuestion;

        insert testConfirmHost;

        
    }

    @isTest
    public static void registrationEmailTest(){
        EventConfirmationEmailHandler eventConfirmationEmailHandler = new EventConfirmationEmailHandler();
        Event_Confirmation__c testConfirm = [SELECT Id, EvEmail__c, EvName__c, EvDateStartDisplay__c, EvAddress__c, EvHostName__c, EvDateStart__c,
            EvDateEnd__c, Email__c, URL__c, Confirmation_Code__c
            FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Test.startTest();
        Messaging.SingleEmailMessage event = eventConfirmationEmailHandler.registrationEmail(testConfirm);
        System.assert(event != null);
        Test.stopTest();
    }

    @isTest
    public static void registrationEmailHostTest(){
        EventConfirmationEmailHandler eventConfirmationEmailHandler = new EventConfirmationEmailHandler();
        Event_Confirmation__c testConfirm = [SELECT Id, EvEmail__c, EvName__c, EvDateStartDisplay__c, EvAddress__c, EvHostName__c, EvDateStart__c,
            EvDateEnd__c, Email__c, URL__c, Confirmation_Code__c
            FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First Host' LIMIT 1];
        Test.startTest();
        Messaging.SingleEmailMessage event = eventConfirmationEmailHandler.registrationEmail(testConfirm);
        System.assert(event != null);
        Test.stopTest();
    }

    @isTest
    public static void hostOrganizerEmailTest(){
        EventConfirmationEmailHandler eventConfirmationEmailHandler = new EventConfirmationEmailHandler();
        Event_Confirmation__c testConfirm = [SELECT Id, EvEmail__c, EvName__c, EvDateStartDisplay__c, EvAddress__c, EvHostName__c, EvDateStart__c,
            EvDateEnd__c, Email__c, Custom_Event__c, Guest_First_Name__c, Guest_Last_Name__c, Contact__c
            FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Test.startTest();
        Event_Question__c eventQuestion = [SELECT Id, Name, Custom_Event__c FROM Event_Question__c WHERE Name = 'Question'];
        Answer__c ans = new Answer__c(Name = '1', Event_Question__c = eventQuestion.Id, Event_Confirmation__c = testConfirm.Id);
        List<Answer__c> answers = new List<Answer__c>();
        answers.add(ans);
        Messaging.SingleEmailMessage event = eventConfirmationEmailHandler.hostOrganizerEmail(testConfirm, answers);
        System.assert(event != null);
        Test.stopTest();
    }
}