force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactSearch_Test.cls
/**
 * @description       : Test class
 * @author            : Eduardo Hernandez
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
@isTest
private class ContactSearch_Test {

    /**Generic Event */
    final Static String EVENTNAME = 'Test Event';

    /**Generic LastName */
    final Static String LASTNAME = 'LastNameSmith';

    @TestSetup
    static void makeData() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User standardUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName);
        insert standardUser;

        System.runAs(standardUser) {
            Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
            Test.testInstall(postinstall, null);
            Test.testInstall(postinstall, new Version(1,0), true);
            Custom_Event__c testEventHost = new Custom_Event__c();
            User userEmail = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
            testEventHost.Name = EVENTNAME;
            testEventHost.Timezone__c = 'CST';
            testEventHost.Address__c = 'Address';
            testEventHost.Duration__c = 60;
            testEventHost.Minutes_Or_Hours__c = 'Minutes';
            testEventHost.Date__c = Datetime.now() + 8;
            testEventHost.Host__c = userEmail.Id;
            insert testEventHost;
            final Contact contactRec = new Contact();
            contactRec.LastName = LASTNAME;
            contactRec.Email = 'EMAILTESTING@TEST.COM';
            insert contactRec;
            Event_Confirmation__c testConfirm = new Event_Confirmation__c(
                Guest_First_Name__c = 'First', Guest_Last_Name__c = 'Last',
                Email__c = 'email@email.com', Check_In__c = false,
                Custom_Event__c = testEventHost.Id,
                Contact__c = contactRec.Id
            );
            insert testConfirm;
        }
    }

    @isTest
    private static void getContacts() {
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Test.startTest();
            List<Contact> lsContacst = [Select Id,Name from Contact];
            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = lsContacst[0].Id;
            Test.setFixedSearchResults(fixedSearchResults);
            final List<Contact> lstContacts = ContactSearch.getContacts(LASTNAME);
            System.assert(lstContacts.size()>0, 'Contact find');
            Test.stopTest();
        }
    }

    @isTest
    private static void getAllReadyInvitedContacts() {
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Test.startTest();
            List<Contact> lsContacst = [Select Id,Name from Contact];
            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = lsContacst[0].Id;
            Test.setFixedSearchResults(fixedSearchResults);
            final Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
            final List<Event_Confirmation__c> lstConfirms = ContactSearch.getAllReadyInvitedContacts(eventId);
            System.assert(lstConfirms.size()>0, 'Contact find');
            Test.stopTest();
        }
    }

    @isTest
    private static void createInvitation() {
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Test.startTest();
            List<Contact> lsContacst = [Select Id,Name from Contact];
            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = lsContacst[0].Id;
            Test.setFixedSearchResults(fixedSearchResults);
            final List<Contact> lstContacts = ContactSearch.getContacts(LASTNAME);
            final List<Id> lstContIds = new List<Id>{lstContacts[0].Id};
            final Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
            final List<Event_Confirmation__c> lstConfirms = ContactSearch.createInvitation(lstContIds, eventId);
            System.assert(lstConfirms.size()>0, 'Confirmation find');
            Test.stopTest();
        }
    }

    @isTest
    private static void sendEmails() {
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Test.startTest();
            List<Contact> lsContacst = [Select Id,Name from Contact];
            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = lsContacst[0].Id;
            Test.setFixedSearchResults(fixedSearchResults);
            final Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
            ContactSearch.sendEmails(eventId);
            Integer invocations = Limits.getEmailInvocations();
            System.AssertEquals(1, invocations, 'An email should be sent');
            Test.stopTest();
        }
    }
}