force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Email_Sended__c.field-meta.xml
<CustomField>
    <fullName>Email_Sended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Sended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventConfirmationCSV.cls
/**
 * @description       : Event  Confirmation CSV
 * @description       : This class is used to get the event confirmations
 * @description       : and return them in a CSV format
 * @author            : Eduardo Hernandez Cuamatzi
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
public with sharing class EventConfirmationCSV {
    /**
    * @description Find event confirmation
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param id Id of the event
    * @return List<Event_Confirmation__c> List of Event results
    **/
    @AuraEnabled(cacheable = true)
    public static List<Event_Confirmation__c> getEventConfirmations(Id id){
        return[SELECT Guest_First_Name__c, Guest_Last_Name__c, Email__c, Check_In__c, Email_Sended__c
            FROM Event_Confirmation__c WHERE Custom_Event__c =: id];
    }
}