force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventConfirmationCSVTest.cls
/**
 * @description       :
 * @author            : Eduardo Hernandez
 * @group             :
 * @last modified on  : 11-03-2023
 * @last modified by  : Eduardo Hernandez
**/
@isTest
private class EventConfirmationCSVTest {
    @isTest
    static void getEventConfirmationsTest() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User standardUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName);
        insert standardUser;

        System.runAs(standardUser) {
            Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
            Test.testInstall(postinstall, null);
            Test.testInstall(postinstall, new Version(1,0), true);
            Custom_Event__c testEvent = new Custom_Event__c();
            testEvent.Name = 'Test Event';
            testEvent.Timezone__c = 'CST';
            testEvent.Address__c = 'Address';
            testEvent.Duration__c = 60;
            testEvent.Minutes_Or_Hours__c = 'Minutes';
            testEvent.Date__c = Datetime.now() + 8;
            testEvent.Host__c = UserInfo.getUserId();
            insert testEvent;
            Event_Confirmation__c testConfirm = new Event_Confirmation__c(
                Guest_First_Name__c = 'First', Guest_Last_Name__c = 'Last',
                Email__c = 'email@email.com', Check_In__c = false,
                Custom_Event__c = testEvent.Id
            );
            insert testConfirm;
            Test.startTest();
            Event_Confirmation__c classEvent = EventConfirmationCSV.getEventConfirmations(testEvent.Id)[0];
            System.assertEquals(testConfirm.Guest_Last_Name__c, classEvent.Guest_Last_Name__c, 'LastName does not match');
            Test.stopTest();
        }
    }
}