force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Time_ZoneStr__c.field-meta.xml
<CustomField>
    <fullName>Time_ZoneStr__c</fullName>
    <label>Time Zone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event4SalesParams__c/Event4SalesParams__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parameters to configure manage package</description>
    <label>Event4Sales</label>
</CustomObject>

force-app/main/default/objects/Event4SalesParams__c/fields/Integer_Param__c.field-meta.xml
<CustomField>
    <fullName>Integer_Param__c</fullName>
    <description>Integer param for hours, employes or days</description>
    <label>Integer Param</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Code__c</fullName>
    <label>Confirmation Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckInController.cls
/**
 * @description       : Check In Controller class
 * @author            : Eduardo Hernandez
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
public without sharing class CheckInController {

    /**Configuration time to start events */
    final static Event4SalesParams__c beforeStartEvent = EventSalesPanel.findParameter('MinimalDaysBeforeEvent');
    /**Configuration time to end events */
    final static Event4SalesParams__c afterStartEvent = EventSalesPanel.findParameter('MaximumDaysAfterEvent');

    /**
    * @description Find event confirmation
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param id 
    * @return Event_Confirmation__c 
    **/
    @AuraEnabled(cacheable = true)
    public static Event_Confirmation__c getEventConfirmation(String id){
        try {
            return[SELECT Id, Check_In__c, Confirmation_Code__c, Custom_Event__r.Date__c, Custom_Event__r.Time_ZoneStr__c FROM Event_Confirmation__c WHERE Id =: id LIMIT 1];    
        } catch (Exception e) {
            return null;
        }
        
    }

    /**
    * @description Retrive events avoid to start
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param id Event to check
    * @return Map<Integer, Datetime> Map with the time to start and end the event
    **/
    @AuraEnabled(cacheable = true)
    public static Map<Integer, Datetime> showEvent(Id id) {
        Map<Integer,Datetime> returnMap = new Map<Integer,Datetime>();
        Event_Confirmation__c event = [SELECT Id, Custom_Event__r.Date__c FROM Event_Confirmation__c WHERE Id =: id LIMIT 1];
        Datetime dateNow = Datetime.now();
        Datetime date2HoursBefore = event.Custom_Event__r.Date__c.addHours(-(Integer.valueOf(beforeStartEvent.Integer_Param__c)));
        Datetime date2HoursAfter = event.Custom_Event__r.Date__c.addHours(-(Integer.valueOf(afterStartEvent.Integer_Param__c)));
        if(dateNow >= date2HoursBefore ){
            if (dateNow <= date2HoursAfter ) {
                returnMap.put(0, dateNow);
            }
            else {
                returnMap.put(1, date2HoursAfter);
            }
        }
        else {
            returnMap.put(-1, date2HoursBefore);
        }
        return returnMap;
    }

    /**
    * @description Update the event confirmation
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param id Event update result
    **/
    @AuraEnabled(cacheable = false)
    public static void updateEventConfirmation(Id id){
        Event_Confirmation__c event = [SELECT Id, Check_In__c FROM Event_Confirmation__c WHERE Id =: id LIMIT 1];
        event.Check_In__c = true;
        update event;
    }
}