force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Email_Sended__c.field-meta.xml
<CustomField>
    <fullName>Email_Sended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Sended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvAddress__c.field-meta.xml
<CustomField>
    <fullName>EvAddress__c</fullName>
    <formula>Custom_Event__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStartDisplay__c.field-meta.xml
<CustomField>
    <fullName>EvDateStartDisplay__c</fullName>
    <formula>LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; &quot; &quot; &amp; 
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))  &gt;  12, LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c + 12 )/24)))),2,&quot;0&quot;), LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))),2,&quot;0&quot;)) &amp; &quot;:&quot; &amp; 
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)&amp; &quot; &quot; &amp;
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24))) &gt;= 12, &apos;PM&apos;, &apos;AM&apos;)
&amp; &quot; &quot; &amp;
TEXT(Custom_Event__r.Timezone__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStartDisplay</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvHostName__c.field-meta.xml
<CustomField>
    <fullName>EvHostName__c</fullName>
    <formula>Custom_Event__r.Host__r.FirstName &amp; &quot; &quot; &amp; Custom_Event__r.Host__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvHostName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvName__c.field-meta.xml
<CustomField>
    <fullName>EvName__c</fullName>
    <formula>Custom_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactSearch.cls
/**
 * @description       : Find Contacts controller
 * @author            : Eduardo Hernandez Cuamatzi
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/

public class ContactSearch {
    /**
    * @description Find contacts by name, email or phone
    * @description       : This method is used to find contacts by name, email or phone
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param textSearch string value to search
    * @return List<Contact> List of Contacts
    **/
    @AuraEnabled(Cacheable = true)
    public static List<Contact> getContacts(String textSearch) {
        List<Contact> contactList = new List<Contact>();
        try {
            for (List<SObject> lsObject: [FIND :textSearch IN ALL FIELDS RETURNING Contact(Id, Name, Email, Phone)]) {
                contactList = (List<Contact>)lsObject;
            }
        } catch (Exception error) {
            System.debug(error.getMessage() + ' '+ error.getCause());
        }
        return contactList;
    }
    /**
    * @description find all ready invited contacts
    * @description       : This method is used to find all ready invited contacts
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param eventId Event related to the contacts
    * @return List<Event_Confirmation__c> Event Confirmation results
    **/
    @AuraEnabled(Cacheable = false)
    public static List<Event_Confirmation__c> getAllReadyInvitedContacts(Id eventId){
        List<Event_Confirmation__c> contactList = [SELECT Id, Contact__c, Custom_Event__c 
        FROM Event_Confirmation__c WHERE Custom_Event__c =: eventId AND Contact__c != null];
        return contactList;
    }

    /**
    * @description Create invitation
    * @description       : This method is used to create invitation
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param ids Contacts Id
    * @param eventId Event Id
    * @return List<Event_Confirmation__c> List of Event Confirmation results
    **/
    @AuraEnabled(Cacheable = false)
    public static List<Event_Confirmation__c> createInvitation(List<String> ids, Id eventId){
        List<Contact> contactList;
        try {
            contactList = [SELECT Id, FirstName, LastName, Email, Phone FROM Contact WHERE Id IN :ids];
        } catch (Exception e) {
            
        }
        List<Event_Confirmation__c> eventConfirmations = new List<Event_Confirmation__c>();
        for (Contact con : contactList) {
            Event_Confirmation__c eventConfirmation = new Event_Confirmation__c();
            eventConfirmation.Custom_Event__c = eventId;
            eventConfirmation.Contact__c = con.Id;
            eventConfirmation.Email__c = con.Email;
            eventConfirmation.Guest_First_Name__c = con.FirstName;
            eventConfirmation.Guest_Last_Name__c = con.LastName;
            eventConfirmations.add(eventConfirmation);
        }
        insert eventConfirmations;
        return eventConfirmations;
    }
    
    /**
    * @description Send emails
    * @description       : This method is used to send emails
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025 
    * @param eventId Event Id
    **/
    @AuraEnabled(Cacheable = false)
    public static void sendEmails(Id eventId){
        List<Event_Confirmation__c> eventConfirmations = [SELECT Id, EvName__c, Custom_Event__c, 
            Email__c, EvDateStartDisplay__c, 
            EvAddress__c, EvHostName__c, Email_Sended__c 
            FROM Event_Confirmation__c WHERE Custom_Event__c =: eventId AND Email_Sended__c = false];

            List<String> emails = new List<String>();

            for (Event_Confirmation__c confirmation : eventConfirmations) {
                emails.add(confirmation.Email__c);
            }

            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();


            String body = '<div>Congratulations!' + '</div>' +
            '<div>You has been invited to an event!' + '</div>' +
            '<div>Event: ' + eventConfirmations[0].EvName__c + '</div>' +
            '<div>Date/Time: ' + eventConfirmations[0].EvDateStartDisplay__c + '</div>' +
            '<div>Address: ' + eventConfirmations[0].EvAddress__c + '</div>' +
            '<div>Host: ' + eventConfirmations[0].EvHostName__c + '</div>' +
            '<div>Link: <a href="' + eventConfirmations[0].Custom_Event__c + '"> '+ eventConfirmations[0].Custom_Event__c+'</a>' + '</div>';

            email.setToAddresses(emails);
            email.setHtmlBody(body);
            email.setSubject(eventConfirmations[0].EvName__c);
        
            emailList.add(email);
            Messaging.sendEmail(emailList);
    }
}