force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/Event_Question__c.object-meta.xml
<CustomObject>
    <label>Event Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Question__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Questions</relationshipLabel>
    <relationshipName>Event_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventConfirmationControllerTest.cls
/**
 * @description       : PostInstall Package
 * @author            : Eduardo Hernandez
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
@isTest
private class EventConfirmationControllerTest {

    @TestSetup
    static void makeData() {
        Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);
        Custom_Event__c testEvent = new Custom_Event__c();
        testEvent.Name = 'Test Event';
        testEvent.Timezone__c = 'CST';
        testEvent.Address__c = 'Address';
        testEvent.Duration__c = 60;
        testEvent.Minutes_Or_Hours__c = 'Minutes';
        testEvent.Date__c = Datetime.now() + 8;
        testEvent.Host__c = UserInfo.getUserId();
        insert testEvent;
        Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
        Event_Confirmation__c testConfirm = new Event_Confirmation__c(
            Guest_First_Name__c = 'First', Guest_Last_Name__c = 'Last',
            Email__c = 'email@email.com', Check_In__c = false,
            Custom_Event__c = eventId
        );
        insert testConfirm;
        Event_Question__c eventQuestion = new Event_Question__c(Name = 'Question', Custom_Event__c = eventId);
        insert eventQuestion;
        Contact con = new Contact(Email = 'email@email.com', FirstName = 'First', LastName = 'Last');
    }

    @isTest
    public static void getCustomEventTest(){
        Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
        Test.startTest();
        Map<String, Object> event = EventConfirmationController.getCustomEvent(eventId);
        System.assert(event.get('eventRecord') != null);
        Test.stopTest();
    }

    @isTest
    public static void createEventConfirmationTest(){
        Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
        String firstName = 'First';
        String lastName = 'Last';
        String email = 'email@email.com';
        Test.startTest();
        Id confId = EventConfirmationController.createEventConfirmation(eventId, firstName, lastName, email);
        System.assert(confId != null);
        Test.stopTest();
        
    }

    @isTest
    public static void answersListTestTrue(){
        List<Map<String,String>> listMap = new List<Map<String,String>>();
        Map<String,String> mapAnswer = new Map<String,String>();
        Event_Confirmation__c testConfirm = [SELECT Id FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Event_Question__c eventQuestionId = [SELECT Id FROM Event_Question__c WHERE Name =: 'Question' LIMIT 1];
        Test.startTest();
        
        mapAnswer.put('key', eventQuestionId.Id);
        mapAnswer.put('value', 'true');
        listMap.add(mapAnswer);
        EventConfirmationController.answersList(listMap, testConfirm.Id);
        Test.stopTest();
    }

    @isTest
    public static void answersListTestFalse(){
        List<Map<String,String>> listMap = new List<Map<String,String>>();
        Map<String,String> mapAnswer = new Map<String,String>();
        Event_Confirmation__c testConfirm = [SELECT Id FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Event_Question__c eventQuestionId = [SELECT Id FROM Event_Question__c WHERE Name =: 'Question' LIMIT 1];
        Test.startTest();
        
        mapAnswer.put('key', eventQuestionId.Id);
        mapAnswer.put('value', 'false');
        listMap.add(mapAnswer);
        EventConfirmationController.answersList(listMap, testConfirm.Id);
        Test.stopTest();
    }

    @isTest
    public static void answersListTestValue(){
        List<Map<String,String>> listMap = new List<Map<String,String>>();
        Map<String,String> mapAnswer = new Map<String,String>();
        Event_Confirmation__c testConfirm = [SELECT Id FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Event_Question__c eventQuestionId = [SELECT Id FROM Event_Question__c WHERE Name =: 'Question' LIMIT 1];
        Test.startTest();
        
        mapAnswer.put('key', eventQuestionId.Id);
        mapAnswer.put('value', 'value');
        listMap.add(mapAnswer);
        EventConfirmationController.answersList(listMap, testConfirm.Id);
        Test.stopTest();
    }

    @isTest
    private static void generateICS() {
        final Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
        final Event_Confirmation__c testConfirm = [Select Id from Event_Confirmation__c where Custom_Event__c =: eventId];
        final Map<String, Object> response = EventConfirmationController.generateICS(testConfirm.Id);
        System.assert(response.containsKey('isOk'), 'ICS Generated');
    }

    @isTest
    public static void updateAnsware() {
        final Custom_Event__c eventRecord = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'];
        Event_Confirmation__c testConfirm = [SELECT Id FROM Event_Confirmation__c WHERE Guest_First_Name__c = 'First' LIMIT 1];
        Event_Question__c eventQuestionId = [SELECT Id FROM Event_Question__c WHERE Name =: 'Question' LIMIT 1];
        Test.startTest();
            eventRecord.Status__c = 'Published';
            update eventRecord;
            eventQuestionId.Required__c = true;
            Database.SaveResult srList = Database.update(eventQuestionId, false);
        Test.stopTest();
        System.assertEquals(srList.isSuccess(), false, 'Update error');
    }
}