force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Type_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Event__c</fullName>
    <label>Type of Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
                <default>true</default>
                <label>Meeting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Question__c/Event_Question__c.object-meta.xml
<CustomObject>
    <label>Event Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Question__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Questions</relationshipLabel>
    <relationshipName>Event_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RelatedQuestionsTriggerTest.cls
/**
 * @description       :
 * @author            : Eduardo Hernandez Cuamatzi
 * @group             :
 * @last modified on  : 11-06-2023
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
@isTest
private class RelatedQuestionsTriggerTest {
    @TestSetup
    static void makeData() {
        Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);
        Custom_Event__c testEvent = new Custom_Event__c();
        testEvent.Name = 'Test Event';
        testEvent.Timezone__c = 'CST';
        testEvent.Address__c = 'Address';
        testEvent.Duration__c = 60;
        testEvent.Minutes_Or_Hours__c = 'Minutes';
        testEvent.Date__c = Datetime.now() + 8;
        testEvent.Host__c = UserInfo.getUserId();
        testEvent.Status__c = 'Published';
        testEvent.Purpose__c = 'Purpose';
        testEvent.Type_of_Event__c = 'Type';
        insert testEvent;

        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName);
        insert u;
    }

    @isTest
    public static void testTriggerInsert(){
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name = 'Test Event'].Id;
            List<Event_Question__c> questionsList = new List<Event_Question__c>();
            for (Integer i = 1; i <= 5; i++) {
                Event_Question__c eventQuestion = new Event_Question__c(Name = 'Question ' + i, Custom_Event__c = eventId);
                questionsList.add(eventQuestion);
            }

            insert questionsList;
            Event_Question__c eventQuestionError = new Event_Question__c(Name = 'Question 6', Custom_Event__c = eventId);
            Boolean exceptionOcurred = false;
            try {
                insert eventQuestionError;
            } catch (Exception e) {
                exceptionOcurred = true;
            }
            System.assert(exceptionOcurred, 'Exception Worked');
        }
    }

    @isTest
    public static void testTriggerUpdate(){
        User standardUser = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com'];
        System.runAs(standardUser) {
            Custom_Event__c event = [SELECT Id, Status__c FROM Custom_Event__c WHERE Name = 'Test Event'];
            event.Status__c = 'Published';
            update event;
            Event_Question__c eventQuestionError = new Event_Question__c(Name = 'Question 6', Custom_Event__c = event.Id);
            insert eventQuestionError;
            eventQuestionError.Name = 'Question Error';
            Boolean exceptionOcurred = false;
            try {
                update eventQuestionError;
            } catch (Exception e) {
                exceptionOcurred = true;
            }
            System.assert(exceptionOcurred, 'Exception Worked');
        }
    }
}