force-app/main/default/objects/Additional_Organizer__c/Additional_Organizer__c.object-meta.xml
<CustomObject>
    <label>Additional Organizer</label>
    <nameField>
        <displayFormat>Add Organizer-{0000}</displayFormat>
        <label>Additional Organizer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Organizer__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Additional Organizers</relationshipLabel>
    <relationshipName>Additional_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Organizer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Additional_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Minutes_Or_Hours__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Or_Hours__c</fullName>
    <label>Minutes Or Hours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
                <label>Eastern</label>
            </value>
            <value>
                <fullName>CST</fullName>
                <label>Central</label>
            </value>
            <value>
                <fullName>MST</fullName>
                <label>Mountain</label>
            </value>
            <value>
                <fullName>PST</fullName>
                <label>Pacific</label>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdditionalOrganaizerHandler_Test.cls
/**
 * @description       : Test class
 * @author            : Eduardo Hernandez
 * @group             : Softtek
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
@isTest
private class AdditionalOrganaizerHandler_Test {

    /**Generic Event */
    final Static String EVENTNAME = 'Test Event';

    /**Generic LastName */
    final Static String LASTNAME = 'LastNameSmith';

    @TestSetup
    static void makeData() {
        Event4Sales_PostInstallPackage postinstall = new Event4Sales_PostInstallPackage();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);
        Custom_Event__c testEventHost = new Custom_Event__c();
        User userEmail = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        testEventHost.Name = EVENTNAME;
        testEventHost.Timezone__c = 'CST';
        testEventHost.Address__c = 'Address';
        testEventHost.Duration__c = 60;
        testEventHost.Minutes_Or_Hours__c = 'Minutes';
        testEventHost.Date__c = Datetime.now() + 8;
        testEventHost.Host__c = userEmail.Id;
        insert testEventHost;
        Profile profileUser = [SELECT Id FROM Profile WHERE Name='Standard User'];
        final String userEmailStr = 'standarduser'+ String.valueOf(Integer.valueOf(Math.random() * 100)) +'@testorg.com';
        User extraUser = new User(
            Alias = 'standt', Email= userEmailStr,
            EmailEncodingKey='UTF-8', LastName= LASTNAME, LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = profileUser.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName=userEmailStr);
        insert extraUser;
        }

    @isTest
    static void additionalOrganizer() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt'];
        System.runAs(standardUser) {
            final Id eventId = [SELECT Id FROM Custom_Event__c WHERE Name =: EVENTNAME].Id;
            final Id organaizerId = [SELECT Id FROM User WHERE LastName =: LASTNAME].Id;
            Additional_Organizer__c extraOrganizer = new Additional_Organizer__c();
            extraOrganizer.Custom_Event__c = eventId;
            extraOrganizer.User__c = organaizerId;
            Test.startTest();
                insert extraOrganizer;
            Test.stopTest();
            System.assertEquals(String.isNotEmpty(extraOrganizer.Id), true, 'Extra Organaizer success');
        }
    }


    @isTest
    static void customEventUpdate() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt'];
        System.runAs(standardUser) {
            final Custom_Event__c eventRecord = [SELECT Id,Date__c FROM Custom_Event__c WHERE Name =: EVENTNAME];
            eventRecord.Date__c = eventRecord.Date__c.addDays(5);
            Test.startTest();
                update eventRecord;
            Test.stopTest();
            System.assertEquals(String.isNotEmpty(eventRecord.Id), true, 'Update success');
        }
    }


    @isTest
    static void customEventUpdateError() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt'];
        System.runAs(standardUser) {
            final Custom_Event__c eventRecord = [SELECT Id,Date__c FROM Custom_Event__c WHERE Name =: EVENTNAME];
            eventRecord.Status__c = 'Published';
            Test.startTest();
                update eventRecord;
                eventRecord.Date__c = eventRecord.Date__c.addDays(-5);
                Database.SaveResult srList = Database.update(eventRecord, false);
            Test.stopTest();
            System.assertEquals(srList.isSuccess(), false, 'Update error');
        }
    }
}