force-app/main/default/objects/Additional_Organizer__c/Additional_Organizer__c.object-meta.xml
<CustomObject>
    <label>Additional Organizer</label>
    <nameField>
        <displayFormat>Add Organizer-{0000}</displayFormat>
        <label>Additional Organizer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Organizer__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Additional Organizers</relationshipLabel>
    <relationshipName>Additional_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Organizer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Additional_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Event_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Event_Confirmation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Confirmation</label>
    <referenceTo>Event_Confirmation__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Event_Question__c.field-meta.xml
<CustomField>
    <fullName>Event_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Question</label>
    <referenceTo>Event_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>CustomEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be assign by default to you in case that you don&apos;t assign another user.</inlineHelpText>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/Event_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Event Confirmation</label>
    <nameField>
        <label>Event Confirmation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Confirmation__c/fields/Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Code__c</fullName>
    <label>Confirmation Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Confirmations</relationshipLabel>
    <relationshipName>Event_Confirmations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvAddress__c.field-meta.xml
<CustomField>
    <fullName>EvAddress__c</fullName>
    <formula>Custom_Event__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateEnd__c.field-meta.xml
<CustomField>
    <fullName>EvDateEnd__c</fullName>
    <formula>MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 0, 4) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440)), 6, 2) &amp;
MID(TEXT(Custom_Event__r.Date__c  + (Custom_Event__r.Duration_Add__c/1440) ), 9, 2) &amp; &quot;T&quot; &amp;
LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;) &amp;
LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c + (Custom_Event__r.Duration_Add__c/1440)))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateEnd</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStart__c.field-meta.xml
<CustomField>
    <fullName>EvDateStart__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;T&quot; &amp;  LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)  
&amp; LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; LPAD(TEXT(SECOND(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStart</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvDateStartDisplay__c.field-meta.xml
<CustomField>
    <fullName>EvDateStartDisplay__c</fullName>
    <formula>LPAD(TEXT(MONTH(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
LPAD(TEXT(DAY(DATEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;) &amp; &quot;/&quot; &amp;
TEXT(YEAR(DATEVALUE(Custom_Event__r.Date__c))) &amp; &quot; &quot; &amp; 
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))  &gt;  12, LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c + 12 )/24)))),2,&quot;0&quot;), LPAD(TEXT(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24)))),2,&quot;0&quot;)) &amp; &quot;:&quot; &amp; 
LPAD(TEXT(MINUTE(TIMEVALUE(Custom_Event__r.Date__c))),2,&quot;0&quot;)&amp; &quot; &quot; &amp;
IF(HOUR(TIMEVALUE(Custom_Event__r.Date__c - ((Custom_Event__r.Hours_to_Add__c )/24))) &gt;= 12, &apos;PM&apos;, &apos;AM&apos;)
&amp; &quot; &quot; &amp;
TEXT(Custom_Event__r.Timezone__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvDateStartDisplay</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvEmail__c.field-meta.xml
<CustomField>
    <fullName>EvEmail__c</fullName>
    <formula>Custom_Event__r.Host__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvHostName__c.field-meta.xml
<CustomField>
    <fullName>EvHostName__c</fullName>
    <formula>Custom_Event__r.Host__r.FirstName &amp; &quot; &quot; &amp; Custom_Event__r.Host__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvHostName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/EvName__c.field-meta.xml
<CustomField>
    <fullName>EvName__c</fullName>
    <formula>Custom_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EvName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Confirmation__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>$Label.Community_URL &amp; &quot;/check-in/?id=&quot; &amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Question__c/Event_Question__c.object-meta.xml
<CustomObject>
    <label>Event Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Question__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Questions</relationshipLabel>
    <relationshipName>Event_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventConfirmationEmailHandler.cls
/**
 * @description       :
 * @author            : Eduardo Hernandez
 * @group             :
 * @last modified on  : 11-11-2025
 * @last modified by  : Eduardo Hernandez Cuamatzi
**/
public without sharing class EventConfirmationEmailHandler {
    /**
    * @description Send confirmation email
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025
    * @param eventConfirmation
    * @return mail
    **/
    public Messaging.SingleEmailMessage registrationEmail(Event_Confirmation__c eventConfirmation){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        String plainText = 'Congratulations!' + '\n' +
            'Here is the event your event file.' +  '\n' +
            'Event: ' + eventConfirmation.EvName__c + '\n' +
            'Date/Time: ' + eventConfirmation.EvDateStartDisplay__c + '\n' +
            'Address: ' + eventConfirmation.EvAddress__c + '\n' +
            'Host: ' + eventConfirmation.EvHostName__c;

        String icsFile = 'BEGIN:VCALENDAR' + '\n' +
            'VERSION:2.0' +  '\n' +
            'PRODID:-//hacksw/handcal//NONSGML v1.0//EN' + '\n' +
            'BEGIN:VEVENT' + '\n' +
            'UID:uid1@example.com' + '\n' +
            'DTSTAMP:' + eventConfirmation.EvDateStart__c + 'Z' + '\n' +
            'DTSTART:' + eventConfirmation.EvDateStart__c + 'Z' + '\n' +
            'DTEND:' + eventConfirmation.EvDateEnd__c + 'Z' + '\n' +
            'SUMMARY:' + eventConfirmation.EvName__c + '\n' +
            'DESCRIPTION:Check in Link: ' + eventConfirmation.URL__c + '\n' +
            '  \\nCode: ' + eventConfirmation.Confirmation_Code__c + '\n' +
            '  \\n**Check in:  From 2 hours before the event start up to 2 hours after the event started**' + '\n' +
            'ORGANIZER;CN=' + eventConfirmation.EvHostName__c + ':mailto:' + eventConfirmation.EvEmail__c + '\n' +
            'STATUS:CONFIRMED' + '\n' +
            'LOCATION:' + eventConfirmation.EvAddress__c + '\n' +
            'BEGIN:VALARM' + '\n' +
            'ACTION:DISPLAY' + '\n' +
            'TRIGGER:-PT2H'  + '\n' +
            'END:VALARM'  + '\n' +
            'END:VEVENT' + '\n' +
            'END:VCALENDAR';

        Blob blobIcs = Blob.valueOf(icsFile);
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(eventConfirmation.EvName__c + '.ics');
        efa.setBody(blobIcs);

        List<String> toAddress = new List<String>();
        toAddress.add(eventConfirmation.Email__c);

        mail.setToAddresses(toAddress);
        mail.setPlainTextBody(plainText);
        mail.setSubject(eventConfirmation.EvName__c);
        mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        return mail;
    }

    /**
    * @description Send confirmation email to host
    * @author Eduardo Hernandez Cuamatzi | 11-11-2025
    * @param eventConfirmation
    * @param answers
    * @return mail
    **/
    public Messaging.SingleEmailMessage hostOrganizerEmail(Event_Confirmation__c eventConfirmation, List<Answer__c> answers){
        Custom_Event__c emailHostOrg = [SELECT Host__r.Email, (SELECT Id, User__r.Email FROM Additional_Organizers__r)
        FROM Custom_Event__c WHERE Id =: eventConfirmation.Custom_Event__c WITH SECURITY_ENFORCED LIMIT 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toAddress = new List<String>();
        toAddress.add(emailHostOrg.Host__r.Email);
        for (Additional_Organizer__c additionalOrganizer : emailHostOrg.Additional_Organizers__r) {
            toAddress.add(additionalOrganizer.User__r.Email);
        }

        String body = '<div>Congratulations!' + '</div>' +
            '<div>Someone registered to your event.' +  '</div>' +
            '<div>First Name: ' + eventConfirmation.Guest_First_Name__c + '</div>' +
            '<div>Last Name: ' + eventConfirmation.Guest_Last_Name__c + '</div>' +
            '<div>Email Address: ' + eventConfirmation.Email__c + '</div>';
        if(eventConfirmation.Contact__c != null){
            body += '<div><a href= "' + URL.getSalesforceBaseUrl().toExternalForm() + '/lightning/r/Contact/' + eventConfirmation.Contact__c + '/view">Contact URL: ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + eventConfirmation.Contact__c + '</a></div>';
        }
        try {

            String answersString = '';

            Map<Id,String> questions = new Map<Id,String>();
            List<Id> ids = new List<Id>();
            for (Answer__c answer : answers) {
                ids.add(answer.Event_Question__c);
            }

            for (Event_Question__c question : [SELECT Name FROM Event_Question__c WHERE Id IN : ids WITH SECURITY_ENFORCED]) {
                questions.put(question.Id, question.Name);
            }

            for (Answer__c answer : answers) {
                answersString += '<div>Question: ' + questions.get(answer.Event_Question__c) + ' Answer: ' + answer.Name + '</div>';
            }
            body += answersString;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + ' '+ e.getCause());
        }

        mail.setToAddresses(toAddress);
        mail.setHtmlBody(body);
        mail.setSubject(eventConfirmation.EvName__c);
        return mail;
    }
}